# Generated by Django 6.0.3 on 2026-03-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='areas',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
