# Generated by Django 6.0.3 on 2026-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='stapel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
