# Generated by Django 5.2.7 on 2026-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_populate_stapel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stapel',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='stapel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
